### ISSUE TITLE
模型大小

### ISSUE THREAD

**Issue by ZhibinPeng** [Xiuyu-Li/q-diffusion#9] opened 2023-06-26 09:54 UTC
为什么量化完后模型大小并没有改变？

**Comment by Xiuyu-Li** [comment] 2023-06-26 16:16
Hi, this is a duplicate of #7 and #3. Please refer to them for the reason. I am planning to release an end-to-end quantized model in the following weeks.

**Closed as completed by Xiuyu-Li** 2023-06-26 16:16 UTC
